language: node_js
node_js:
  - '0.10'
before_script:
  - 'gem update --system'
  - 'gem install sass'
  - 'gem install susy'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
services: mongodb
after_script:
  - cat coverage/**/lcov.info | codeclimate
  - codeclimate < test/coverage/**/lcov.info
